// Generator function to create a sequence of numbers
function* numberGenerator(start, end) {
    for (let i = start; i <= end; i++) {
      yield i; // Yield the current number and pause execution
    }
  }
  
  // Create an iterator from the generator function
  const iterator = numberGenerator(1, 5);
  
  // Iterate through the values generated by the iterator
  for (let number of iterator) {
    console.log(number); // Output: 1, 2, 3, 4, 5
  }
  
  // Example of manual iteration using the iterator's next() method
  const manualIterator = numberGenerator(10, 12);
  console.log(manualIterator.next().value); // Output: 10
  console.log(manualIterator.next().value); // Output: 11
  console.log(manualIterator.next().value); // Output: 12
  console.log(manualIterator.next().done);  // Output: true (indicates completion)
  